name: CD - Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nodeJS
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm i

      - name: Build app
        run: cd frontend/ && npm run build

      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just a placeholder'

      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST}}:/var/www/html/origindigital

      - name: Migrate database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/rayj
            ls
            npm run db:migrate
            npm run db:seed
